// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// altTab
void altTab();
RcppExport SEXP _winsendkeys_altTab() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    altTab();
    return R_NilValue;
END_RCPP
}
// loopTest
void loopTest();
RcppExport SEXP _winsendkeys_loopTest() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    loopTest();
    return R_NilValue;
END_RCPP
}
// sendKeys
void sendKeys(CharacterVector x);
RcppExport SEXP _winsendkeys_sendKeys(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    sendKeys(x);
    return R_NilValue;
END_RCPP
}
// activateWindow
void activateWindow(CharacterVector x);
RcppExport SEXP _winsendkeys_activateWindow(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    activateWindow(x);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_winsendkeys_altTab", (DL_FUNC) &_winsendkeys_altTab, 0},
    {"_winsendkeys_loopTest", (DL_FUNC) &_winsendkeys_loopTest, 0},
    {"_winsendkeys_sendKeys", (DL_FUNC) &_winsendkeys_sendKeys, 1},
    {"_winsendkeys_activateWindow", (DL_FUNC) &_winsendkeys_activateWindow, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_winsendkeys(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
