# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
altTab <- function() {
    invisible(.Call(`_winsendkeys_altTab`))
}

#' @export
loopTest <- function() {
    invisible(.Call(`_winsendkeys_loopTest`))
}

#' @title Send keys to active window
#' @references \url{https://www.codeproject.com/Articles/6819/SendKeys-in-C}
#' @export
#' @examples
#' sendKeys("{DELAY=50}@rnotepad{ENTER}")
#' sendKeys("{DELAY=50}@rchrome{ENTER}{DELAY=300}m{DELAY=50}irai-solutions^{ENTER}")
sendKeys <- function(x) {
    invisible(.Call(`_winsendkeys_sendKeys`, x))
}

#' @title Activate window
#' @export
#' @examples
#' activateWindow("Notepad")
activateWindow <- function(x) {
    invisible(.Call(`_winsendkeys_activateWindow`, x))
}

