# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['3.6.3', '4.4.1', 'release']

    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck, covr

      # below includes a sub-step to show testthat output
      - uses: r-lib/actions/check-r-package@v2

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }} && matrix.r-version == 'release'
        uses: codecov/test-results-action@v1
        with:
          files: check/*.Rcheck/tests/junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Analyze and upload test coverage
        if: success() && matrix.r-version == 'release'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          Rscript scripts/runCodecov.R
